server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://uat-db:3306/orderdb
    username: uat_user
    password: uat_password

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

app:
  jwt:
    secret: mySuperSecureJwtSecretKeyForUatEnv1234567890123456
    expiration: 3600000

springdoc:
  swagger-ui:
    enabled: true

logging:
  level:
    root: WARN