apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: springboot-app
type: Opaque
data:
  DB_USERNAME: dXNlcg==        # base64 encoded "user"
  DB_PASSWORD: cGFzc3dvcmQ=    # base64 encoded "password"