apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "springboot-app.fullname" . }}-{{ .Values.deploymentColor }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "springboot-app.name" . }}
      color: {{ .Values.deploymentColor }}
  template:
    metadata:
      labels:
        app: {{ include "springboot-app.name" . }}
        color: {{ .Values.deploymentColor }}
    spec:
      containers:
        - name: springboot-app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.containerPort }}
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: {{ .Values.containerPort }}
            initialDelaySeconds: 10
            periodSeconds: 10