apiVersion: v1
kind: Service
metadata:
  name: {{ include "springboot-app.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "springboot-app.name" . }}
    color: {{ .Values.deploymentColor }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}